refactor: building
We use our own file server for our CCBlueX/mcef fork. The script generates binaries for every platform and includes hashes with the ZIP which will be uploaded to our LiquidBounce API.

diff --git a/.github/workflows/build-jcef.yml b/.github/workflows/build-jcef.yml
--- a/.github/workflows/build-jcef.yml
+++ b/.github/workflows/build-jcef.yml
@@ -2,62 +2,46 @@ name: Build java-cef
 
 on:
   push:
-    branches:
-      - master
   workflow_dispatch:
 
 jobs:
   java-cef-linux:
-    runs-on: [ubuntu-20.04]
+    runs-on: [ubuntu-24.04]
     strategy:
       matrix:
         platform: [amd64, arm64]
     steps:
-      - name: Upload mask
-        run: echo "::add-mask::${{ secrets.UPLOAD_URL }}"
       - uses: actions/checkout@v4
-      - name: Setup JDK
-        uses: actions/setup-java@v4
-        with:
-          java-version: '8'
-          distribution: 'temurin'
       - name: Install deps and build
         run: |
           sudo apt update
-          sudo apt install build-essential g++ cmake ninja-build python3 libgtk2.0-dev s3cmd -y
+          sudo apt install build-essential g++ cmake ninja-build openjdk-17-jdk python3 libgtk2.0-dev -y
           mkdir jcef_build && cd jcef_build
           cmake -G "Ninja" -DPROJECT_ARCH=${{ matrix.platform }} -DCMAKE_BUILD_TYPE=Release ..
           ninja -j4
           mv native/Release linux_${{ matrix.platform }}
           strip linux_${{ matrix.platform }}/libcef.so
-          tar -czf linux_${{ matrix.platform }}.tar.gz linux_${{ matrix.platform }}
+          python3 ../.github/workflows/scripts/generate_hash.py linux_${{ matrix.platform }}
+          mv linux_${{ matrix.platform }}/.hash ./
+          tar -czf linux_${{ matrix.platform }}.tar.gz linux_${{ matrix.platform }} .hash
           sha256sum linux_${{ matrix.platform }}.tar.gz > linux_${{ matrix.platform }}.tar.gz.sha256
-      - name: Copy s3cfg
-        run: echo "${{ secrets.S3_CFG }}" > ~/.s3cfg
-      - name: Upload java-cef build
-        run: |
-          s3cmd put -P /home/runner/work/java-cef/java-cef/jcef_build/linux_${{ matrix.platform }}.tar.gz s3://mcef-us-1/java-cef-builds/${{ github.sha }}/linux_${{ matrix.platform }}.tar.gz
-          s3cmd put -P /home/runner/work/java-cef/java-cef/jcef_build/linux_${{ matrix.platform }}.tar.gz.sha256 s3://mcef-us-1/java-cef-builds/${{ github.sha }}/linux_${{ matrix.platform }}.tar.gz.sha256
+      - uses: actions/upload-artifact@v4
+        if: ${{ github.ref == 'refs/heads/main' }}
+        with:
+          name: 'linux_${{ matrix.platform }}'
+          path: |
+            jcef_build/linux_${{ matrix.platform }}.tar.gz
+            jcef_build/linux_${{ matrix.platform }}.tar.gz.sha256
+          if-no-files-found: error
+
   java-cef-windows:
     runs-on: [windows-2022]
     strategy:
       matrix:
         platform: [amd64, arm64]
     steps:
-      - name: Upload mask
-        run: echo "::add-mask::${{ secrets.UPLOAD_URL }}"
       - uses: actions/checkout@v4
-      - name: Setup JDK
-        uses: actions/setup-java@v4
-        with:
-          java-version: '8'
-          distribution: 'temurin'
       - uses: ilammy/msvc-dev-cmd@v1
-      - name: Install s3cmd
-        run: |
-          pip install python-dateutil
-          Invoke-WebRequest -Uri "https://github.com/s3tools/s3cmd/archive/master.zip" -OutFile "D:\s3cmd.zip"
-          Expand-Archive -Path "D:\s3cmd.zip" -DestinationPath "D:\s3cmd"
       - name: Build
         run: |
           mkdir jcef_build && cd jcef_build
@@ -67,42 +51,95 @@ jobs:
           ren Release windows_${{ matrix.platform }}
           cd ..
           move native/windows_${{ matrix.platform }} windows_${{ matrix.platform }}
-          tar -czf windows_${{ matrix.platform }}.tar.gz windows_${{ matrix.platform }}
+          python3 ../.github/workflows/scripts/generate_hash.py windows_${{ matrix.platform }}
+          mv windows_${{ matrix.platform }}/.hash ./
+          tar -czf windows_${{ matrix.platform }}.tar.gz windows_${{ matrix.platform }} .hash
           Get-FileHash -Algorithm SHA256 -Path "windows_${{ matrix.platform }}.tar.gz" | Out-File "windows_${{ matrix.platform }}.tar.gz.sha256"
-      - name: Copy s3cfg
-        run: echo "${{ secrets.S3_CFG }}" > "$HOME\AppData\Roaming\s3cmd.ini"
-      - name: Upload java-cef build
-        run: |
-          python D:\s3cmd\s3cmd-master\s3cmd put -P D:\a\java-cef\java-cef\jcef_build\windows_${{ matrix.platform }}.tar.gz s3://mcef-us-1/java-cef-builds/${{ github.sha }}/windows_${{ matrix.platform }}.tar.gz
-          python D:\s3cmd\s3cmd-master\s3cmd put -P D:\a\java-cef\java-cef\jcef_build\windows_${{ matrix.platform }}.tar.gz.sha256 s3://mcef-us-1/java-cef-builds/${{ github.sha }}/windows_${{ matrix.platform }}.tar.gz.sha256
+      - uses: actions/upload-artifact@v4
+        if: ${{ github.ref == 'refs/heads/main' }}
+        with:
+          name: 'windows_${{ matrix.platform }}'
+          path: |
+            jcef_build/windows_${{ matrix.platform }}.tar.gz
+            jcef_build/windows_${{ matrix.platform }}.tar.gz.sha256
+          if-no-files-found: error
+
   java-cef-macos:
-    runs-on: [macos-12]
+    runs-on: [macos-13]
     strategy:
       matrix:
         platform: [amd64, arm64]
     steps:
-      - name: Upload mask
-        run: echo "::add-mask::${{ secrets.UPLOAD_URL }}"
       - uses: actions/checkout@v4
-      - name: Setup JDK
-        uses: actions/setup-java@v4
+      - name: Set up Python 3.9
+        uses: actions/setup-python@v4
         with:
-          java-version: '8'
-          distribution: 'temurin'
+          python-version: '3.9'
       - run: |
           brew install ninja
           brew install coreutils
-          brew install s3cmd
-          sudo xcode-select --switch /Applications/Xcode_13.1.app
+          sudo xcode-select -s /Applications/Xcode.app
           mkdir jcef_build && cd jcef_build
           cmake -G "Ninja" -DPROJECT_ARCH=${{ matrix.platform }} -DCMAKE_BUILD_TYPE=Release ..
           ninja -j4
           mv native/Release macos_${{ matrix.platform }}
-          tar -czf macos_${{ matrix.platform }}.tar.gz macos_${{ matrix.platform }}
+          python3 ../.github/workflows/scripts/generate_hash.py macos_${{ matrix.platform }}
+          mv macos_${{ matrix.platform }}/.hash ./
+          tar -czf macos_${{ matrix.platform }}.tar.gz macos_${{ matrix.platform }} .hash
           sha256sum macos_${{ matrix.platform }}.tar.gz > macos_${{ matrix.platform }}.tar.gz.sha256
-      - name: Copy s3cfg
-        run: echo "${{ secrets.S3_CFG }}" > ~/.s3cfg
-      - name: Upload java-cef build
+      - uses: actions/upload-artifact@v4
+        if: ${{ github.ref == 'refs/heads/main' }}
+        with:
+          name: 'macos_${{ matrix.platform }}'
+          path: |
+            jcef_build/macos_${{ matrix.platform }}.tar.gz
+            jcef_build/macos_${{ matrix.platform }}.tar.gz.sha256
+          if-no-files-found: error
+  check-secret:
+    runs-on: ubuntu-24.04
+    if: github.ref == 'refs/heads/main'
+    steps:
+      - name: Check secret
+        env:
+          API_TOKEN: ${{ secrets.API_TOKEN }}
         run: |
-          s3cmd put -P /Users/runner/work/java-cef/java-cef/jcef_build/macos_${{ matrix.platform }}.tar.gz s3://mcef-us-1/java-cef-builds/${{ github.sha }}/macos_${{ matrix.platform }}.tar.gz
-          s3cmd put -P /Users/runner/work/java-cef/java-cef/jcef_build/macos_${{ matrix.platform }}.tar.gz.sha256 s3://mcef-us-1/java-cef-builds/${{ github.sha }}/macos_${{ matrix.platform }}.tar.gz.sha256
+          if [ -z "$API_TOKEN" ]; then
+            echo "API_TOKEN is not set. Upload will not proceed."
+            exit 1
+          fi
+          echo "API_TOKEN is set. Upload can proceed."
+
+  upload-to-api:
+    needs: [java-cef-linux, java-cef-windows, java-cef-macos, check-secret]
+    runs-on: ubuntu-24.04
+    if: github.ref == 'refs/heads/main'
+    strategy:
+      matrix:
+        platform: [linux_amd64, linux_arm64, windows_amd64, windows_arm64, macos_amd64, macos_arm64]
+    steps:
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ matrix.platform }}
+      - name: Upload to LiquidBounce API
+        env:
+          API_TOKEN: ${{ secrets.API_TOKEN }}
+        run: |
+          PLATFORM="${{ matrix.platform }}"
+          
+          response=$(curl -w "\n%{http_code}" -X POST \
+            -H "Authorization: Bearer $API_TOKEN" \
+            -H "Content-Type: application/gzip" \
+            --data-binary "@${PLATFORM}.tar.gz" \
+            "http://nossl.api.liquidbounce.net/api/v3/resource/mcef-cef/${{ github.sha }}/${PLATFORM}")
+          
+          status_code=$(echo "$response" | tail -n1)
+          response_body=$(echo "$response" | sed '$d')
+          
+          echo "Status code: $status_code"
+          echo "Response body: $response_body"
+          
+          if [ "$status_code" -lt 200 ] || [ "$status_code" -ge 300 ]; then
+            echo "Upload failed with status code $status_code"
+            exit 1
+          fi
